# -*- coding: utf-8 -*-
"""M1_Trabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OPQ-L1glVhofhdgBrTm1TeGgtuN3TXX
"""

print('\033[0;31m-*' * 12, '\nCalculadora Inteligente')
print('-*' * 12)  # Apresenta a calculadora

continuar = "S"
while continuar == "S":
  numero1 = float(input('\033[mDigite um número: '))
  numero2 = float(input('Digite outro número: '))
  print('-*' * 12, """
[1] Para somar
[2] Para subtrair
[3] Para multiplicar
[4] Para dividir
[5] Para calcular porcentagem
""", '-*' * 12)
  opcao = int(input('Qual opção você gostaria? '))
  if opcao == 1:
    resultado = numero1 + numero2
    print(f'A soma de {numero1} com {numero2} é {resultado}.')
    continuar = str(input('Gostaria de recomeçar (S/N)? ')).upper().strip()
  elif opcao == 2:
    resultado = numero1 - numero2
    print(f'A subtração entre {numero1} e {numero2} é {resultado}.')
    continuar = str(input('Gostaria de recomeçar (S/N)? ')).upper().strip()
  elif opcao == 3:
    resultado = numero1 * numero2
    print(f'A multiplicação de {numero1} por {numero2} é {resultado}.')
    continuar = str(input('Gostaria de recomeçar (S/N)? ')).upper().strip()
  elif opcao == 4:
    resultado = numero1 / numero2
    print(f'A divisão de {numero1} por {numero2} é {resultado:.2f}')
    continuar = str(input('Gostaria de recomeçar (S/N)? ')).upper().strip()
  elif opcao == 5:
    resultado = numero1 * (numero2 / 100)
    print(f'{numero2} porcento de {numero1} é {resultado}.')
    continuar = str(input('Gostaria de recomeçar (S/N)? ')).upper().strip()
  else:
    continuar = str(input("""Não existe a opção que você digitou.
    Gostaria de tentar de novo (S/N): """)).upper().strip()
  print('--' * 12)
print("Espero ter ajudado!")
